name: RabiSystem
version: '1.0'
main: cn.rabitown.rabisystem.RabiSystem
api-version: '1.21'
authors: [ opaup ]
softdepend: [ TAB, LibsDisguises, ProtocolLib ]

permissions:
  rabisystem.admin:
    default: op
  rabisystem.use:
    default: true

commands:
  rabi:
    description: RabiSystem 主指令
    aliases: [rs]
  wl:
    description: 白名单接受指令
    usage: /wl <accept|deny>
    whitelist: # 覆盖原版 whitelist 指令
      description: 白名单管理
      usage: /whitelist <accept|deny>